name: Automated Forensic Triage
on: [push]
jobs:
  triage-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Voer Forensische Analyse uit
        run: |
          python3 triage.py /home/forensicadmin/evidence/forenisch-image-portfolio.vhdx > rapport.txt
      - name: Upload het Triage Rapport
        uses: actions/upload-artifact@v4
        with:
          name: Forensic-Report-Result
          path: rapport.txt
